### ISSUE TITLE
upload/download artifacts with versions in the names

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#61]
To facilitate #46 , and following example on http://datasets.datalad.org/datalad/packages/windows/ , artifacts should be uploaded with versions in the file names

ATM we have e.g. for windows build:
```
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
          name: git-annex-windows-installer
          path: git-annex\git-annex-installer.exe
      
  test-annex:
    runs-on: windows-2016
    needs: build-package
    steps:
    - name: Download git-annex installer
      uses: actions/download-artifact@v2
      with:
        name: git-annex-windows-installer
```
so ideally the `name` itself should carry a version (so when looking at the artifact in github web ui we could see what version it corresponds to), but most likely that is not feasible (unless @jwodder does magic and says that "it is simple"), so we would need to rename `git-annex-installer.exe` itself and installation
```
    - name: Install git-annex package
      shell: powershell
      run: ./git-annex-installer.exe /S
```
step hopefully could tollerate a glob , e.g. to become
```
      run: ./git-annex-installer_*.exe /S
``` 

edit: note that it should be done also for neurodebian and osx artifacts.
